---
# Installs and configures web server
# Copies over code
# Enables the Application as a Service

##### SETUP DEPENDENCIES #####

# Update and Upgrade
- name: Update and Upgrade
  apt:
    upgrade: dist
    update_cache: yes
  become: yes

# Install required software 
- name: Install software
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - nginx
    - nodejs
    - npm
  become: yes

# Symlink nodejs to node
# This is needed as ubuntu is annoying
- name: nodejs to node symlink
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
  become: yes