---
##### NGINX CONFIGURATION #####

# touch relevant files and directories
- name: create pid and logs directory
  file:
    path: /usr/share/nginx/{{ item }}
    state: directory
  with_items:
    - pids
    - logs
  become: yes

- name: touch required files
  file: 
    path: /usr/share/nginx/{{ item }}
    state: touch
  with_items:
    - "logs/access.log"
    - "logs/error.log"
    - "pids/nginx.pid"
  become: yes

# Copy over NGiNX config
- name: Copy NGiNX Config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: yes

# Restart and enable nginx
- name: enable and restart nginx
  service:
    name: nginx
    state: started
    enabled: yes